name: postviritu
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - polars>=1.0
  - pyyaml>=6.0
  - pandas>=1.0
  - mmseqs2>=15
  - blast
  - taxonkit>=0.15
  - pytaxonkit>=0.10
  - requests>=2.0
  - numpy
  - pip
  - pip:
      - -e .
